const dns = require("dns");
dns.setServers(["8.8.8.8", "8.8.4.4"]);
const path = require("path");
const mongoose = require("mongoose");
require("dotenv").config({ path: path.join(__dirname, "../.env") });
const Product = require(path.join(__dirname, "../models/Product"));
const products = [
  // ===== ELECTRONICS =====
  {
    name: "Smart Watch Pro",
    price: 49.99,
    originalPrice: 89.99,
    discount: 44,
    category: "Electronics",
    subcategory: "Smart watches",
    isHot: true,
    image:
      "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=300&q=80",
    images: [
      "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&q=80",
    ],
    rating: 4.5,
    reviews: 128,
    orders: 95,
    stock: 50,
    verified: true,
    brand: "TechBrand",
    shipping: "Worldwide shipping",
    condition: "Brand new",
    type: "Smart Watch",
    material: "Aluminum",
    design: "Modern",
    customization: "Custom strap",
    protection: "Refund Policy",
    warranty: "1 year",
    description:
      "Sleek smartwatch with health tracking, GPS, and 7-day battery life.",
    specs: {
      Model: "SW-001",
      Style: "Modern",
      Certificate: "CE",
      Size: "44mm",
      Memory: "N/A",
    },
    features: [
      "Heart rate monitor",
      "Sleep tracking",
      "Water resistant",
      "7-day battery",
    ],
  },
  {
    name: "Sony Headphones WH-1000XM5",
    price: 249.99,
    originalPrice: 349.99,
    discount: 28,
    category: "Electronics",
    subcategory: "Headphones",
    isHot: true,
    image:
      "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=300&q=80",
    images: [
      "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&q=80",
      "https://images.unsplash.com/photo-1484704849700-f032a568e944?w=600&q=80",
    ],
    rating: 4.9,
    reviews: 567,
    orders: 320,
    stock: 30,
    verified: true,
    brand: "Sony",
    shipping: "Worldwide shipping",
    condition: "Brand new",
    type: "Headphones",
    material: "Plastic/Metal",
    design: "Over-ear",
    customization: "Custom colors",
    protection: "Refund Policy",
    warranty: "1 year",
    description:
      "Industry leading noise cancellation with 30-hour battery life.",
    specs: {
      Model: "WH-1000XM5",
      Style: "Over-ear",
      Certificate: "CE/FCC",
      Size: "Standard",
      Memory: "N/A",
    },
    features: [
      "Industry-leading ANC",
      "30-hour battery",
      "Multipoint connection",
      "Quick charge",
    ],
  },
  {
    name: "Samsung Galaxy S24",
    price: 699.99,
    originalPrice: 899.99,
    discount: 22,
    category: "Electronics",
    subcategory: "Smartphones",
    isHot: true,
    image:
      "https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=300&q=80",
    images: [
      "https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=600&q=80",
    ],
    rating: 4.6,
    reviews: 234,
    orders: 189,
    stock: 40,
    verified: true,
    brand: "Samsung",
    shipping: "Worldwide shipping",
    condition: "Brand new",
    type: "Smartphone",
    material: "Titanium/Glass",
    design: "Modern",
    customization: "N/A",
    protection: "Refund Policy",
    warranty: "1 year",
    description: "Powerful Samsung Galaxy with AI features and 200MP camera.",
    specs: {
      Model: "Galaxy S24",
      Style: "Bar",
      Certificate: "CE/FCC",
      Size: "162x79mm",
      Memory: "12GB RAM",
    },
    features: [
      "200MP camera",
      "AI features",
      "5000mAh battery",
      "120Hz display",
    ],
  },
  {
    name: "iPhone 15 Pro",
    price: 999.99,
    originalPrice: 1199.99,
    discount: 16,
    category: "Electronics",
    subcategory: "Smartphones",
    isHot: true,
    image:
      "https://images.unsplash.com/photo-1678685888221-cda773a3dcdb?w=300&q=80",
    images: [
      "https://images.unsplash.com/photo-1678685888221-cda773a3dcdb?w=600&q=80",
    ],
    rating: 4.9,
    reviews: 512,
    orders: 445,
    stock: 25,
    verified: true,
    brand: "Apple",
    shipping: "Worldwide shipping",
    condition: "Brand new",
    type: "Smartphone",
    material: "Titanium",
    design: "Premium",
    customization: "N/A",
    protection: "Refund Policy",
    warranty: "1 year",
    description: "Most advanced iPhone with titanium design and A17 Pro chip.",
    specs: {
      Model: "iPhone 15 Pro",
      Style: "Premium",
      Certificate: "CE/FCC",
      Size: "159x76mm",
      Memory: "8GB RAM",
    },
    features: ["A17 Pro chip", "Titanium design", "USB-C", "Action Button"],
  },
  {
    name: "Apple Watch SE",
    price: 199.99,
    originalPrice: 279.99,
    discount: 28,
    category: "Electronics",
    subcategory: "Smart watches",
    image:
      "https://images.unsplash.com/photo-1434494878577-86c23bcb06b9?w=300&q=80",
    images: [
      "https://images.unsplash.com/photo-1434494878577-86c23bcb06b9?w=600&q=80",
    ],
    rating: 4.5,
    reviews: 198,
    orders: 150,
    stock: 35,
    verified: true,
    brand: "Apple",
    shipping: "Worldwide shipping",
    condition: "Brand new",
    type: "Smart Watch",
    material: "Aluminum",
    design: "Modern",
    customization: "Custom bands",
    protection: "Refund Policy",
    warranty: "1 year",
    description: "Powerful smartwatch with health sensors and all-day battery.",
    specs: {
      Model: "Watch SE",
      Style: "Modern",
      Certificate: "CE/FCC",
      Size: "44mm",
      Memory: "N/A",
    },
    features: ["Heart rate monitor", "Fall detection", "GPS", "50m waterproof"],
  },

  // ===== COMPUTER AND TECH =====
  {
    name: "MacBook Air M2",
    price: 999.99,
    originalPrice: 1199.99,
    discount: 16,
    category: "Computer and tech",
    subcategory: "Laptops",
    isHot: true,
    image:
      "https://images.unsplash.com/photo-1611186871525-9b3e3a9e6dd2?w=300&q=80",
    images: [
      "https://images.unsplash.com/photo-1611186871525-9b3e3a9e6dd2?w=600&q=80",
      "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=600&q=80",
    ],
    rating: 4.8,
    reviews: 342,
    orders: 278,
    stock: 20,
    verified: true,
    brand: "Apple",
    shipping: "Worldwide shipping",
    condition: "Brand new",
    type: "Laptop",
    material: "Aluminum",
    design: "Slim",
    customization: "Custom engraving",
    protection: "Refund Policy",
    warranty: "1 year",
    description: "Supercharged by M2 chip. 18-hour battery, fanless design.",
    specs: {
      Model: "MacBook Air M2",
      Style: "Slim",
      Certificate: "CE/FCC",
      Size: "30x21cm",
      Memory: "8GB RAM",
    },
    features: [
      "M2 chip",
      "18-hour battery",
      "Fanless design",
      "Retina display",
    ],
  },
  {
    name: "Lenovo Laptop i7",
    price: 749.99,
    originalPrice: 999.99,
    discount: 25,
    category: "Computer and tech",
    subcategory: "Laptops",
    image:
      "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=300&q=80",
    images: [
      "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=600&q=80",
    ],
    rating: 4.5,
    reviews: 234,
    orders: 180,
    stock: 18,
    verified: true,
    brand: "Lenovo",
    shipping: "Worldwide shipping",
    condition: "Brand new",
    type: "Laptop",
    material: "Aluminum",
    design: "Professional",
    customization: "N/A",
    protection: "Refund Policy",
    warranty: "1 year",
    description: "Powerful Intel i7 laptop for professionals and power users.",
    specs: {
      Model: "Lenovo i7",
      Style: "Professional",
      Certificate: "CE/FCC",
      Size: "35x24cm",
      Memory: "16GB RAM",
    },
    features: [
      "Intel i7 processor",
      "512GB SSD",
      "Full HD display",
      "Fast charging",
    ],
  },
  {
    name: "Gaming Headset RGB",
    price: 59.99,
    originalPrice: 99.99,
    discount: 40,
    category: "Computer and tech",
    subcategory: "Gaming",
    isHot: true,
    image:
      "https://images.unsplash.com/photo-1599669454699-248893623440?w=300&q=80",
    images: [
      "https://images.unsplash.com/photo-1599669454699-248893623440?w=600&q=80",
    ],
    rating: 4.3,
    reviews: 178,
    orders: 220,
    stock: 45,
    verified: true,
    brand: "GamePro",
    shipping: "Worldwide shipping",
    condition: "Brand new",
    type: "Gaming Headset",
    material: "Plastic/Metal",
    design: "Gaming",
    customization: "Custom RGB",
    protection: "Refund Policy",
    warranty: "1 year",
    description:
      "Immersive gaming headset with 7.1 surround sound and RGB lighting.",
    specs: {
      Model: "GH-RGB",
      Style: "Gaming",
      Certificate: "CE",
      Size: "Standard",
      Memory: "N/A",
    },
    features: [
      "7.1 surround sound",
      "RGB lighting",
      "Noise cancelling mic",
      "50mm drivers",
    ],
  },
  {
    name: "Canon EOS R50",
    price: 679.99,
    originalPrice: 899.99,
    discount: 24,
    category: "Computer and tech",
    subcategory: "Cameras",
    image:
      "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=300&q=80",
    images: [
      "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=600&q=80",
    ],
    rating: 4.8,
    reviews: 212,
    orders: 145,
    stock: 12,
    verified: true,
    brand: "Canon",
    shipping: "Worldwide shipping",
    condition: "Brand new",
    type: "Mirrorless Camera",
    material: "Plastic/Metal",
    design: "Professional",
    customization: "N/A",
    protection: "Refund Policy",
    warranty: "1 year",
    description: "Professional mirrorless camera for stunning 4K photography.",
    specs: {
      Model: "EOS R50",
      Style: "Mirrorless",
      Certificate: "CE/FCC",
      Size: "116x85mm",
      Memory: "N/A",
    },
    features: [
      "24.2MP sensor",
      "4K video",
      "Eye-tracking AF",
      "Compact design",
    ],
  },

  // ===== HOME INTERIORS =====
  {
    name: "Ergonomic Chair",
    price: 189.99,
    originalPrice: 249.99,
    discount: 24,
    category: "Home interiors",
    subcategory: "Furniture",
    image:
      "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=300&q=80",
    images: [
      "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&q=80",
    ],
    rating: 4.4,
    reviews: 76,
    orders: 45,
    stock: 25,
    verified: true,
    brand: "ComfortPlus",
    shipping: "Worldwide shipping",
    condition: "Brand new",
    type: "Chair",
    material: "Mesh/Steel",
    design: "Ergonomic",
    customization: "Custom colors",
    protection: "Refund Policy",
    warranty: "2 years",
    description:
      "Premium ergonomic chair for all-day comfort and back support.",
    specs: {
      Model: "EC-001",
      Style: "Ergonomic",
      Certificate: "N/A",
      Size: "Standard",
      Memory: "N/A",
    },
    features: [
      "Lumbar support",
      "Adjustable height",
      "Breathable mesh",
      "360° swivel",
    ],
  },
  {
    name: "Modern Sofa Set",
    price: 599.99,
    originalPrice: 799.99,
    discount: 25,
    category: "Home interiors",
    subcategory: "Furniture",
    image:
      "https://images.unsplash.com/photo-1540518614846-7eded433c457?w=300&q=80",
    images: [
      "https://images.unsplash.com/photo-1540518614846-7eded433c457?w=600&q=80",
    ],
    rating: 4.6,
    reviews: 45,
    orders: 30,
    stock: 10,
    verified: true,
    brand: "HomeLux",
    shipping: "Worldwide shipping",
    condition: "Brand new",
    type: "Sofa",
    material: "Fabric/Wood",
    design: "Modern",
    customization: "Custom fabric",
    protection: "Refund Policy",
    warranty: "3 years",
    description: "Elegant modern sofa set perfect for any living room.",
    specs: {
      Model: "SS-001",
      Style: "Modern",
      Certificate: "N/A",
      Size: "220x85cm",
      Memory: "N/A",
    },
    features: [
      "Premium fabric",
      "Solid wood frame",
      "Removable covers",
      "Easy assembly",
    ],
  },
  {
    name: "Coffee Maker Deluxe",
    price: 89.99,
    originalPrice: 129.99,
    discount: 30,
    category: "Home interiors",
    subcategory: "Kitchen",
    image:
      "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=300&q=80",
    images: [
      "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=600&q=80",
    ],
    rating: 4.7,
    reviews: 143,
    orders: 190,
    stock: 22,
    verified: true,
    brand: "BrewMaster",
    shipping: "Worldwide shipping",
    condition: "Brand new",
    type: "Coffee Maker",
    material: "Stainless Steel",
    design: "Modern",
    customization: "N/A",
    protection: "Refund Policy",
    warranty: "2 years",
    description:
      "Brew perfect coffee with programmable settings and 12-cup capacity.",
    specs: {
      Model: "CM-DLX",
      Style: "Modern",
      Certificate: "CE",
      Size: "25x18x35cm",
      Memory: "N/A",
    },
    features: [
      "Programmable timer",
      "12-cup capacity",
      "Keep warm",
      "Auto shutoff",
    ],
  },
  {
    name: "Kitchen Mixer Pro",
    price: 129.99,
    originalPrice: 199.99,
    discount: 35,
    category: "Home interiors",
    subcategory: "Kitchen",
    image:
      "https://images.unsplash.com/photo-1507272931001-fc06c17e4f43?w=300&q=80",
    images: [
      "https://images.unsplash.com/photo-1507272931001-fc06c17e4f43?w=600&q=80",
    ],
    rating: 4.4,
    reviews: 67,
    orders: 89,
    stock: 20,
    verified: true,
    brand: "KitchenPro",
    shipping: "Worldwide shipping",
    condition: "Brand new",
    type: "Kitchen Appliance",
    material: "Stainless Steel",
    design: "Professional",
    customization: "N/A",
    protection: "Refund Policy",
    warranty: "2 years",
    description: "Professional stand mixer with 10 speed settings and 5L bowl.",
    specs: {
      Model: "KM-PRO",
      Style: "Professional",
      Certificate: "CE",
      Size: "38x22x35cm",
      Memory: "N/A",
    },
    features: [
      "10 speed settings",
      "5L stainless bowl",
      "Multiple attachments",
      "1000W motor",
    ],
  },
  {
    name: "Electric Kettle Pro",
    price: 34.99,
    originalPrice: 59.99,
    discount: 41,
    category: "Home interiors",
    subcategory: "Kitchen",
    image:
      "https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=300&q=80",
    images: [
      "https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=600&q=80",
    ],
    rating: 4.4,
    reviews: 89,
    orders: 160,
    stock: 60,
    verified: true,
    brand: "BrewFast",
    shipping: "Worldwide shipping",
    condition: "Brand new",
    type: "Electric Kettle",
    material: "Stainless Steel",
    design: "Modern",
    customization: "N/A",
    protection: "Refund Policy",
    warranty: "1 year",
    description:
      "Fast boiling kettle with temperature control and keep-warm function.",
    specs: {
      Model: "EK-PRO",
      Style: "Modern",
      Certificate: "CE",
      Size: "22x14x25cm",
      Memory: "N/A",
    },
    features: [
      "1.7L capacity",
      "Temperature control",
      "Keep warm 30min",
      "Auto shutoff",
    ],
  },

  // ===== CLOTHES AND WEAR =====
  {
    name: "Men's Cotton T-Shirt",
    price: 12.99,
    originalPrice: 24.99,
    discount: 48,
    category: "Clothes and wear",
    subcategory: "T-Shirts",
    image:
      "https://images.unsplash.com/photo-1581655353564-df123a1eb820?w=300&q=80",
    images: [
      "https://images.unsplash.com/photo-1581655353564-df123a1eb820?w=600&q=80",
      "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=600&q=80",
    ],
    rating: 4.3,
    reviews: 89,
    orders: 230,
    stock: 100,
    verified: true,
    brand: "FashionHub",
    shipping: "Worldwide shipping",
    condition: "Brand new",
    type: "T-Shirt",
    material: "100% Cotton",
    design: "Casual",
    customization: "Custom print available",
    protection: "Refund Policy",
    warranty: "N/A",
    description:
      "Comfortable everyday cotton t-shirt available in multiple colors.",
    specs: {
      Model: "TS-001",
      Style: "Casual",
      Certificate: "N/A",
      Size: "S/M/L/XL/XXL",
      Memory: "N/A",
    },
    features: [
      "100% cotton",
      "Machine washable",
      "Multiple colors",
      "Slim fit",
    ],
  },
  {
    name: "Leather Wallet Brown",
    price: 29.99,
    originalPrice: 49.99,
    discount: 40,
    category: "Clothes and wear",
    subcategory: "Accessories",
    image:
      "https://images.unsplash.com/photo-1627123424574-724758594e93?w=300&q=80",
    images: [
      "https://images.unsplash.com/photo-1627123424574-724758594e93?w=600&q=80",
    ],
    rating: 4.6,
    reviews: 145,
    orders: 310,
    stock: 60,
    verified: true,
    brand: "LeatherCo",
    shipping: "Worldwide shipping",
    condition: "Brand new",
    type: "Wallet",
    material: "Genuine Leather",
    design: "Classic",
    customization: "Custom engraving",
    protection: "Refund Policy",
    warranty: "6 months",
    description:
      "Premium genuine leather wallet with 8 card slots and RFID blocking.",
    specs: {
      Model: "WL-BR01",
      Style: "Bifold",
      Certificate: "N/A",
      Size: "11x9cm",
      Memory: "N/A",
    },
    features: [
      "Genuine leather",
      "8 card slots",
      "RFID blocking",
      "Slim design",
    ],
  },
  {
    name: "Travel Bag Canvas",
    price: 45.99,
    originalPrice: 79.99,
    discount: 42,
    category: "Clothes and wear",
    subcategory: "Bags",
    image:
      "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=300&q=80",
    images: [
      "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&q=80",
    ],
    rating: 4.5,
    reviews: 201,
    orders: 178,
    stock: 55,
    verified: true,
    brand: "TravelPro",
    shipping: "Worldwide shipping",
    condition: "Brand new",
    type: "Travel Bag",
    material: "Canvas",
    design: "Casual",
    customization: "Custom print",
    protection: "Refund Policy",
    warranty: "1 year",
    description:
      "Spacious canvas travel bag with laptop sleeve and multiple compartments.",
    specs: {
      Model: "TB-001",
      Style: "Casual",
      Certificate: "N/A",
      Size: "45x30x20cm",
      Memory: "N/A",
    },
    features: [
      "Large capacity",
      "Laptop sleeve",
      "Multiple pockets",
      "Durable material",
    ],
  },
  {
    name: "Winter Coat Brown",
    price: 89.99,
    originalPrice: 149.99,
    discount: 40,
    category: "Clothes and wear",
    subcategory: "Coats",
    image:
      "https://images.unsplash.com/photo-1548549557-dbe9946621da?w=300&q=80",
    images: [
      "https://images.unsplash.com/photo-1548549557-dbe9946621da?w=600&q=80",
    ],
    rating: 4.4,
    reviews: 67,
    orders: 89,
    stock: 45,
    verified: true,
    brand: "WinterWear",
    shipping: "Worldwide shipping",
    condition: "Brand new",
    type: "Winter Coat",
    material: "Wool blend",
    design: "Classic",
    customization: "Custom sizing",
    protection: "Refund Policy",
    warranty: "N/A",
    description:
      "Warm and stylish winter coat for cold weather, wool blend material.",
    specs: {
      Model: "WC-BR02",
      Style: "Classic",
      Certificate: "N/A",
      Size: "M/L/XL",
      Memory: "N/A",
    },
    features: [
      "Warm wool blend",
      "Water resistant",
      "Multiple pockets",
      "Classic design",
    ],
  },

  // ===== SPORTS AND OUTDOOR =====
  {
    name: "Running Shoes Nike Air",
    price: 89.99,
    originalPrice: 129.99,
    discount: 30,
    category: "Sports and outdoor",
    subcategory: "Footwear",
    image:
      "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=300&q=80",
    images: [
      "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&q=80",
    ],
    rating: 4.7,
    reviews: 312,
    orders: 450,
    stock: 80,
    verified: true,
    brand: "SportMax",
    shipping: "Worldwide shipping",
    condition: "Brand new",
    type: "Running Shoes",
    material: "Mesh/Rubber",
    design: "Athletic",
    customization: "Custom size",
    protection: "Refund Policy",
    warranty: "6 months",
    description:
      "Lightweight running shoes with superior cushioning and breathability.",
    specs: {
      Model: "RS-AIR",
      Style: "Athletic",
      Certificate: "N/A",
      Size: "6-12 UK",
      Memory: "N/A",
    },
    features: [
      "Lightweight design",
      "Superior cushioning",
      "Breathable mesh",
      "Anti-slip sole",
    ],
  },
  {
    name: "Yoga Mat Premium",
    price: 24.99,
    originalPrice: 44.99,
    discount: 44,
    category: "Sports and outdoor",
    subcategory: "Fitness",
    image:
      "https://images.unsplash.com/photo-1601925228139-e1a294b4d0e7?w=300&q=80",
    images: [
      "https://images.unsplash.com/photo-1601925228139-e1a294b4d0e7?w=600&q=80",
    ],
    rating: 4.5,
    reviews: 189,
    orders: 340,
    stock: 70,
    verified: true,
    brand: "FitLife",
    shipping: "Worldwide shipping",
    condition: "Brand new",
    type: "Yoga Mat",
    material: "TPE/Rubber",
    design: "Non-slip",
    customization: "Custom color",
    protection: "Refund Policy",
    warranty: "1 year",
    description:
      "Eco-friendly premium yoga mat with non-slip surface and carrying strap.",
    specs: {
      Model: "YM-PRO",
      Style: "Standard",
      Certificate: "N/A",
      Size: "183x61cm",
      Memory: "N/A",
    },
    features: [
      "Non-slip surface",
      "6mm thick",
      "Eco-friendly TPE",
      "Carrying strap included",
    ],
  },
  {
    name: "Camping Tent 4-Person",
    price: 149.99,
    originalPrice: 219.99,
    discount: 31,
    category: "Sports and outdoor",
    subcategory: "Camping",
    image:
      "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=300&q=80",
    images: [
      "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=600&q=80",
    ],
    rating: 4.6,
    reviews: 95,
    orders: 120,
    stock: 25,
    verified: true,
    brand: "OutdoorPro",
    shipping: "Worldwide shipping",
    condition: "Brand new",
    type: "Camping Tent",
    material: "Polyester",
    design: "Dome",
    customization: "N/A",
    protection: "Refund Policy",
    warranty: "2 years",
    description:
      "Waterproof 4-person dome tent with easy setup and ventilation system.",
    specs: {
      Model: "CT-4P",
      Style: "Dome",
      Certificate: "N/A",
      Size: "240x210x130cm",
      Memory: "N/A",
    },
    features: [
      "Waterproof 3000mm",
      "Easy 5-min setup",
      "4-person capacity",
      "Ventilation windows",
    ],
  },

  // ===== TOOLS & EQUIPMENTS =====
  {
    name: "Cordless Drill Set",
    price: 69.99,
    originalPrice: 99.99,
    discount: 30,
    category: "Tools, equipments",
    subcategory: "Power Tools",
    image:
      "https://images.unsplash.com/photo-1504148455328-c376907d081c?w=300&q=80",
    images: [
      "https://images.unsplash.com/photo-1504148455328-c376907d081c?w=600&q=80",
    ],
    rating: 4.5,
    reviews: 156,
    orders: 200,
    stock: 35,
    verified: true,
    brand: "ToolMaster",
    shipping: "Worldwide shipping",
    condition: "Brand new",
    type: "Power Tool",
    material: "Metal/Plastic",
    design: "Professional",
    customization: "N/A",
    protection: "Refund Policy",
    warranty: "2 years",
    description:
      "18V cordless drill with 2 batteries, charger and 25-piece bit set.",
    specs: {
      Model: "CD-18V",
      Style: "Professional",
      Certificate: "CE",
      Size: "Standard",
      Memory: "N/A",
    },
    features: [
      "18V lithium battery",
      "2 speed settings",
      "LED work light",
      "25-piece bit set",
    ],
  },
  {
    name: "Tool Box Complete Set",
    price: 49.99,
    originalPrice: 79.99,
    discount: 37,
    category: "Tools, equipments",
    subcategory: "Hand Tools",
    image:
      "https://images.unsplash.com/photo-1581244277943-fe4a9c777189?w=300&q=80",
    images: [
      "https://images.unsplash.com/photo-1581244277943-fe4a9c777189?w=600&q=80",
    ],
    rating: 4.4,
    reviews: 89,
    orders: 160,
    stock: 50,
    verified: true,
    brand: "ToolMaster",
    shipping: "Worldwide shipping",
    condition: "Brand new",
    type: "Tool Set",
    material: "Chrome Vanadium Steel",
    design: "Classic",
    customization: "N/A",
    protection: "Refund Policy",
    warranty: "Lifetime",
    description:
      "Complete 108-piece tool set for home repairs and DIY projects.",
    specs: {
      Model: "TB-108",
      Style: "Classic",
      Certificate: "CE",
      Size: "108 pieces",
      Memory: "N/A",
    },
    features: [
      "108 pieces",
      "Chrome vanadium steel",
      "Hard carry case",
      "All sizes included",
    ],
  },

  // ===== ANIMAL AND PETS =====
  {
    name: "Pet Carrier Bag",
    price: 34.99,
    originalPrice: 54.99,
    discount: 36,
    category: "Animal and pets",
    subcategory: "Pet Travel",
    image:
      "https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=300&q=80",
    images: [
      "https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=600&q=80",
    ],
    rating: 4.6,
    reviews: 78,
    orders: 130,
    stock: 40,
    verified: true,
    brand: "PetCo",
    shipping: "Worldwide shipping",
    condition: "Brand new",
    type: "Pet Carrier",
    material: "Oxford/Mesh",
    design: "Portable",
    customization: "Custom colors",
    protection: "Refund Policy",
    warranty: "1 year",
    description:
      "Airline-approved pet carrier bag with ventilation and safety leash.",
    specs: {
      Model: "PC-001",
      Style: "Portable",
      Certificate: "N/A",
      Size: "45x25x25cm",
      Memory: "N/A",
    },
    features: [
      "Airline approved",
      "Mesh ventilation",
      "Safety leash inside",
      "Washable pad",
    ],
  },
  {
    name: "Dog Food Premium 5kg",
    price: 29.99,
    originalPrice: 44.99,
    discount: 33,
    category: "Animal and pets",
    subcategory: "Pet Food",
    image:
      "https://images.unsplash.com/photo-1589924691995-400dc9ecc119?w=300&q=80",
    images: [
      "https://images.unsplash.com/photo-1589924691995-400dc9ecc119?w=600&q=80",
    ],
    rating: 4.7,
    reviews: 234,
    orders: 500,
    stock: 100,
    verified: true,
    brand: "PetNutrition",
    shipping: "Worldwide shipping",
    condition: "Brand new",
    type: "Pet Food",
    material: "N/A",
    design: "N/A",
    customization: "N/A",
    protection: "Refund Policy",
    warranty: "See expiry",
    description:
      "Premium dry dog food with real chicken and vegetables for adult dogs.",
    specs: {
      Model: "DF-5KG",
      Style: "Dry Food",
      Certificate: "Vet Approved",
      Size: "5kg bag",
      Memory: "N/A",
    },
    features: [
      "Real chicken protein",
      "No artificial colors",
      "Vet approved",
      "All breeds",
    ],
  },

  // ===== MACHINERY TOOLS =====
  {
    name: "Angle Grinder 850W",
    price: 79.99,
    originalPrice: 119.99,
    discount: 33,
    category: "Machinery tools",
    subcategory: "Grinders",
    image:
      "https://images.unsplash.com/photo-1572981779307-38b8cabb2407?w=300&q=80",
    images: [
      "https://images.unsplash.com/photo-1572981779307-38b8cabb2407?w=600&q=80",
    ],
    rating: 4.4,
    reviews: 112,
    orders: 145,
    stock: 30,
    verified: true,
    brand: "PowerMax",
    shipping: "Worldwide shipping",
    condition: "Brand new",
    type: "Angle Grinder",
    material: "Metal",
    design: "Professional",
    customization: "N/A",
    protection: "Refund Policy",
    warranty: "2 years",
    description:
      "Heavy duty 850W angle grinder for cutting, grinding and polishing.",
    specs: {
      Model: "AG-850",
      Style: "Professional",
      Certificate: "CE",
      Size: "Standard",
      Memory: "N/A",
    },
    features: [
      "850W motor",
      "4.5 inch disc",
      "Safety guard",
      "Adjustable handle",
    ],
  },
  {
    name: "Air Compressor 50L",
    price: 199.99,
    originalPrice: 279.99,
    discount: 28,
    category: "Machinery tools",
    subcategory: "Compressors",
    image:
      "https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=300&q=80",
    images: [
      "https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=600&q=80",
    ],
    rating: 4.5,
    reviews: 67,
    orders: 80,
    stock: 15,
    verified: true,
    brand: "PowerMax",
    shipping: "Worldwide shipping",
    condition: "Brand new",
    type: "Air Compressor",
    material: "Metal",
    design: "Industrial",
    customization: "N/A",
    protection: "Refund Policy",
    warranty: "2 years",
    description:
      "50L oil-free air compressor for pneumatic tools and tire inflation.",
    specs: {
      Model: "AC-50L",
      Style: "Industrial",
      Certificate: "CE",
      Size: "50L tank",
      Memory: "N/A",
    },
    features: ["50L tank", "Oil-free pump", "2HP motor", "Pressure regulator"],
  },

  // ===== AUTOMOBILES =====
  {
    name: "Car Dash Camera 4K",
    price: 89.99,
    originalPrice: 139.99,
    discount: 35,
    category: "Automobiles",
    subcategory: "Car Electronics",
    image:
      "https://images.unsplash.com/photo-1449965408869-eaa3f722e40d?w=300&q=80",
    images: [
      "https://images.unsplash.com/photo-1449965408869-eaa3f722e40d?w=600&q=80",
    ],
    rating: 4.6,
    reviews: 189,
    orders: 260,
    stock: 45,
    verified: true,
    brand: "DriveSafe",
    shipping: "Worldwide shipping",
    condition: "Brand new",
    type: "Dash Camera",
    material: "Plastic",
    design: "Compact",
    customization: "N/A",
    protection: "Refund Policy",
    warranty: "1 year",
    description: "4K dash camera with night vision, GPS and parking mode.",
    specs: {
      Model: "DC-4K",
      Style: "Compact",
      Certificate: "CE/FCC",
      Size: "75x40x35mm",
      Memory: "N/A",
    },
    features: ["4K recording", "Night vision", "GPS tracking", "Parking mode"],
  },
  {
    name: "Car Seat Cover Set",
    price: 39.99,
    originalPrice: 64.99,
    discount: 38,
    category: "Automobiles",
    subcategory: "Car Accessories",
    image:
      "https://images.unsplash.com/photo-1503736334956-4c8f8e92946d?w=300&q=80",
    images: [
      "https://images.unsplash.com/photo-1503736334956-4c8f8e92946d?w=600&q=80",
    ],
    rating: 4.3,
    reviews: 134,
    orders: 290,
    stock: 60,
    verified: true,
    brand: "AutoStyle",
    shipping: "Worldwide shipping",
    condition: "Brand new",
    type: "Seat Cover",
    material: "Leather/Fabric",
    design: "Universal",
    customization: "Custom colors",
    protection: "Refund Policy",
    warranty: "1 year",
    description:
      "Universal fit car seat cover set with anti-slip base and easy install.",
    specs: {
      Model: "SC-UNI",
      Style: "Universal",
      Certificate: "N/A",
      Size: "Universal fit",
      Memory: "N/A",
    },
    features: [
      "Universal fit",
      "Anti-slip base",
      "Easy installation",
      "Washable fabric",
    ],
  },

  // ===== GIFT BOXES =====
  {
    name: "Luxury Spa Gift Set",
    price: 89.99,
    originalPrice: 129.99,
    discount: 30,
    category: "Gift boxes",
    subcategory: "Wellness",
    isHot: false,
    isGift: true,
    giftOccasion: "Birthday",
    image:
      "https://images.unsplash.com/photo-1607006344380-b6775a0824c8?w=300&q=80",
    images: [
      "https://images.unsplash.com/photo-1607006344380-b6775a0824c8?w=600&q=80",
    ],
    rating: 4.8,
    reviews: 156,
    orders: 210,
    stock: 40,
    verified: true,
    brand: "GiftCo",
    shipping: "Worldwide shipping",
    condition: "Brand new",
    type: "Gift Box",
    material: "Mixed",
    design: "Premium",
    customization: "Custom message card",
    protection: "Refund Policy",
    warranty: "N/A",
    description:
      "Aromatherapy candles, bath salts, body lotion & more. Perfect birthday gift.",
    specs: {
      Model: "GB-SPA",
      Style: "Luxury",
      Certificate: "N/A",
      Size: "6 items",
      Memory: "N/A",
    },
    features: [
      "6 premium items",
      "Gift wrapped",
      "Custom message card",
      "Free shipping",
    ],
  },
  {
    name: "Gourmet Food Hamper",
    price: 65.99,
    originalPrice: 89.99,
    discount: 26,
    category: "Gift boxes",
    subcategory: "Food",
    isHot: false,
    isGift: true,
    giftOccasion: "Corporate",
    image:
      "https://images.unsplash.com/photo-1606914469633-bd45b4e76440?w=300&q=80",
    images: [
      "https://images.unsplash.com/photo-1606914469633-bd45b4e76440?w=600&q=80",
    ],
    rating: 4.7,
    reviews: 203,
    orders: 340,
    stock: 55,
    verified: true,
    brand: "GiftCo",
    shipping: "Worldwide shipping",
    condition: "Brand new",
    type: "Gift Box",
    material: "Mixed",
    design: "Classic",
    customization: "Custom branding available",
    protection: "Refund Policy",
    warranty: "N/A",
    description:
      "Premium chocolates, nuts, dried fruits & artisan snacks. Great for corporate gifting.",
    specs: {
      Model: "GB-FOOD",
      Style: "Classic",
      Certificate: "N/A",
      Size: "12 items",
      Memory: "N/A",
    },
    features: [
      "12 gourmet items",
      "Elegant hamper basket",
      "Corporate branding",
      "Free delivery",
    ],
  },
  {
    name: "Kids Fun Activity Pack",
    price: 45.99,
    originalPrice: 69.99,
    discount: 34,
    category: "Gift boxes",
    subcategory: "Kids",
    isHot: false,
    isGift: true,
    giftOccasion: "Birthday",
    image:
      "https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=300&q=80",
    images: [
      "https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=600&q=80",
    ],
    rating: 4.6,
    reviews: 118,
    orders: 190,
    stock: 65,
    verified: true,
    brand: "GiftCo",
    shipping: "Worldwide shipping",
    condition: "Brand new",
    type: "Gift Box",
    material: "Mixed",
    design: "Colorful",
    customization: "Add child's name",
    protection: "Refund Policy",
    warranty: "N/A",
    description:
      "Puzzles, coloring books, stickers & educational toys. Perfect for kids aged 4-10.",
    specs: {
      Model: "GB-KIDS",
      Style: "Fun",
      Certificate: "N/A",
      Size: "8 items",
      Memory: "N/A",
    },
    features: [
      "8 fun items",
      "Age 4-10",
      "Educational toys",
      "Personalized name tag",
    ],
  },
  {
    name: "Green Living Eco Box",
    price: 72.99,
    originalPrice: 99.99,
    discount: 27,
    category: "Gift boxes",
    subcategory: "Home",
    isHot: false,
    isGift: true,
    giftOccasion: "Any",
    image:
      "https://images.unsplash.com/photo-1610508500445-a4592435e27e?w=300&q=80",
    images: [
      "https://images.unsplash.com/photo-1610508500445-a4592435e27e?w=600&q=80",
    ],
    rating: 4.5,
    reviews: 89,
    orders: 145,
    stock: 30,
    verified: true,
    brand: "EcoGift",
    shipping: "Worldwide shipping",
    condition: "Brand new",
    type: "Gift Box",
    material: "Eco-friendly",
    design: "Natural",
    customization: "Custom message",
    protection: "Refund Policy",
    warranty: "N/A",
    description:
      "Eco-friendly home essentials & sustainable products. Great for any occasion.",
    specs: {
      Model: "GB-ECO",
      Style: "Natural",
      Certificate: "N/A",
      Size: "5 items",
      Memory: "N/A",
    },
    features: [
      "5 eco items",
      "100% sustainable",
      "Recycled packaging",
      "Carbon neutral",
    ],
  },
  {
    name: "Tech Enthusiast Bundle",
    price: 119.99,
    originalPrice: 169.99,
    discount: 29,
    category: "Gift boxes",
    subcategory: "Tech",
    isHot: true,
    isGift: true,
    giftOccasion: "Corporate",
    image:
      "https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=300&q=80",
    images: [
      "https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=600&q=80",
    ],
    rating: 4.9,
    reviews: 267,
    orders: 410,
    stock: 25,
    verified: true,
    brand: "TechGift",
    shipping: "Worldwide shipping",
    condition: "Brand new",
    type: "Gift Box",
    material: "Mixed",
    design: "Modern",
    customization: "Custom engraving",
    protection: "Refund Policy",
    warranty: "N/A",
    description:
      "Gadget accessories, cables, smart tools & power bank. Perfect for tech lovers.",
    specs: {
      Model: "GB-TECH",
      Style: "Modern",
      Certificate: "CE",
      Size: "7 items",
      Memory: "N/A",
    },
    features: [
      "7 tech gadgets",
      "Premium packaging",
      "Custom engraving",
      "Express delivery",
    ],
  },
  {
    name: "Coffee Lover's Gift Set",
    price: 55.99,
    originalPrice: 79.99,
    discount: 30,
    category: "Gift boxes",
    subcategory: "Food",
    isHot: false,
    isGift: true,
    giftOccasion: "Any",
    image:
      "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=300&q=80",
    images: [
      "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=600&q=80",
    ],
    rating: 4.7,
    reviews: 134,
    orders: 280,
    stock: 50,
    verified: true,
    brand: "GiftCo",
    shipping: "Worldwide shipping",
    condition: "Brand new",
    type: "Gift Box",
    material: "Mixed",
    design: "Classic",
    customization: "Custom message card",
    protection: "Refund Policy",
    warranty: "N/A",
    description:
      "Single-origin beans, French press, travel mug & biscuits for coffee lovers.",
    specs: {
      Model: "GB-COFFEE",
      Style: "Classic",
      Certificate: "N/A",
      Size: "4 items",
      Memory: "N/A",
    },
    features: [
      "4 premium items",
      "Single-origin beans",
      "French press included",
      "Gift wrapped",
    ],
  },
  {
    name: "Fitness Starter Kit",
    price: 95.99,
    originalPrice: 139.99,
    discount: 31,
    category: "Gift boxes",
    subcategory: "Sports",
    isHot: false,
    isGift: true,
    giftOccasion: "Birthday",
    image:
      "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=300&q=80",
    images: [
      "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=600&q=80",
    ],
    rating: 4.6,
    reviews: 98,
    orders: 175,
    stock: 35,
    verified: true,
    brand: "FitGift",
    shipping: "Worldwide shipping",
    condition: "Brand new",
    type: "Gift Box",
    material: "Mixed",
    design: "Athletic",
    customization: "Custom name print",
    protection: "Refund Policy",
    warranty: "N/A",
    description:
      "Resistance bands, yoga mat, shaker bottle & protein bars for fitness beginners.",
    specs: {
      Model: "GB-FIT",
      Style: "Athletic",
      Certificate: "N/A",
      Size: "6 items",
      Memory: "N/A",
    },
    features: [
      "6 fitness items",
      "Beginner friendly",
      "Nutrition guide included",
      "Carry bag",
    ],
  },
  {
    name: "Baby Welcome Box",
    price: 79.99,
    originalPrice: 109.99,
    discount: 27,
    category: "Gift boxes",
    subcategory: "Kids",
    isHot: false,
    isGift: true,
    giftOccasion: "Baby Shower",
    image:
      "https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=300&q=80",
    images: [
      "https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=600&q=80",
    ],
    rating: 4.9,
    reviews: 312,
    orders: 520,
    stock: 45,
    verified: true,
    brand: "BabyGift",
    shipping: "Worldwide shipping",
    condition: "Brand new",
    type: "Gift Box",
    material: "Organic/Soft",
    design: "Cute",
    customization: "Baby name embroidery",
    protection: "Refund Policy",
    warranty: "N/A",
    description:
      "Soft toys, organic onesie, blanket & baby care essentials for newborns.",
    specs: {
      Model: "GB-BABY",
      Style: "Cute",
      Certificate: "CE Safety",
      Size: "9 items",
      Memory: "N/A",
    },
    features: [
      "9 baby items",
      "Organic materials",
      "CE safety certified",
      "Name embroidery",
    ],
  },
];

async function seedProducts() {
  try {
    await mongoose.connect(process.env.MONGO_URI, { family: 4 });
    console.log("MongoDB Connected ✅");
    await Product.deleteMany({});
    console.log("Old products deleted 🗑️");
    const inserted = await Product.insertMany(products);
    console.log(`✅ ${inserted.length} products seeded successfully!`);
    console.log("\nCategories seeded:");
    const cats = [...new Set(products.map((p) => p.category))];
    cats.forEach((cat) => {
      const count = products.filter((p) => p.category === cat).length;
      console.log(`  ${cat}: ${count} products`);
    });
    process.exit(0);
  } catch (err) {
    console.error("Seed error:", err);
    process.exit(1);
  }
}

seedProducts();
